DROP DATABASE IF EXISTS gamegogs_database;

CREATE DATABASE IF NOT EXISTS gamegogs_database;

USE gamegogs_database;

CREATE TABLE countries(
   id_country INT AUTO_INCREMENT,
  country_name VARCHAR(255) NOT NULL,
  country_code VARCHAR(5) NOT NULL,
   PRIMARY KEY(id_country)
);

CREATE TABLE users(
   id_user INT AUTO_INCREMENT,
   user_nikename VARCHAR(50) NOT NULL,
   user_birthdate DATE,
   user_email VARCHAR(50) NOT NULL,
   user_signin_date DATETIME NOT NULL,
   user_password_hash VARCHAR(255),
   PRIMARY KEY(id_user),
   UNIQUE(user_nikename),
   UNIQUE(user_email)
);

CREATE TABLE categories(
   id_categorie INT AUTO_INCREMENT,
   category_name VARCHAR(50) NOT NULL,
   PRIMARY KEY(id_categorie)
);

CREATE TABLE manufacturers(
   id_manufacturer INT AUTO_INCREMENT,
   manufacturer_name VARCHAR(50) NOT NULL,
   PRIMARY KEY(id_manufacturer)
);

CREATE TABLE dates(
   id_dates INT AUTO_INCREMENT,
   date_year SMALLINT NOT NULL,
   PRIMARY KEY(id_dates)
);

CREATE TABLE medias(
   id_medias INT AUTO_INCREMENT,
   media_type VARCHAR(50) NOT NULL,
   media_storage_capacity VARCHAR(20) NOT NULL,
   media_faces TINYINT NOT NULL,
   PRIMARY KEY(id_medias)
);

CREATE TABLE emails(
   Id_emails INT AUTO_INCREMENT,
   email VARCHAR(50) NOT NULL,
   email_date DATETIME,
   browser VARCHAR(50),
   mobile_browser VARCHAR(50),
   operating_system VARCHAR(50),
   server_adress VARCHAR(50),
   server_name VARCHAR(50),
   remote_adress VARCHAR(50),
   remote_host VARCHAR(50),
   remote_port VARCHAR(50),
   remote_user VARCHAR(50),
   PRIMARY KEY(Id_emails),
   UNIQUE(email)
);

CREATE TABLE configuration(
   Id_configuration INT AUTO_INCREMENT,
   browser VARCHAR(50),
   operating_system VARCHAR(50),
   server_adress VARCHAR(50),
   server_name VARCHAR(128),
   remote_adress VARCHAR(50),
   remote_port VARCHAR(50),
   PRIMARY KEY(Id_configuration)
);

CREATE TABLE state(
   id_state INT AUTO_INCREMENT,
   copie_state_rank VARCHAR(10) NOT NULL,
   copie_state_name VARCHAR(50) NOT NULL,
   copie_state_description VARCHAR(50) NOT NULL,
   PRIMARY KEY(id_state)
);

CREATE TABLE editors(
   id_editor INT AUTO_INCREMENT,
   editor_name VARCHAR(50) NOT NULL,
   id_country INT NOT NULL,
   PRIMARY KEY(id_editor),
   FOREIGN KEY(id_country) REFERENCES countries(id_country)
);

CREATE TABLE machines(
   id_machine INT AUTO_INCREMENT,
   machine_model VARCHAR(50) NOT NULL,
   machine_releasedate VARCHAR(7) NOT NULL,
   machine_label_picture VARCHAR(100),
   machine_type VARCHAR(50),
   gamepad_connexion_type VARCHAR(50),
   cpu_type VARCHAR(50),
   id_manufacturer INT NOT NULL,
   PRIMARY KEY(id_machine),
   FOREIGN KEY(id_manufacturer) REFERENCES manufacturers(id_manufacturer)
);

CREATE TABLE games(
   id_game INT AUTO_INCREMENT,
   game_title VARCHAR(50) NOT NULL,
   game_subtitle VARCHAR(50),
   game_reference VARCHAR(50) NOT NULL,
   game_cover VARCHAR(100),
   id_dates INT NOT NULL,
   id_editor INT NOT NULL,
   PRIMARY KEY(id_game),
   FOREIGN KEY(id_dates) REFERENCES dates(id_dates),
   FOREIGN KEY(id_editor) REFERENCES editors(id_editor)
);

CREATE TABLE copie(
   id_copie INT AUTO_INCREMENT,
   copie_price DECIMAL(19,4),
   copie_addition_date DATETIME NOT NULL,
   id_machine INT NOT NULL,
   id_user INT NOT NULL,
   id_state INT NOT NULL,
   id_medias INT NOT NULL,
   id_game INT NOT NULL,
   PRIMARY KEY(id_copie),
   FOREIGN KEY(id_machine) REFERENCES machines(id_machine),
   FOREIGN KEY(id_user) REFERENCES users(id_user),
   FOREIGN KEY(id_state) REFERENCES state(id_state),
   FOREIGN KEY(id_medias) REFERENCES medias(id_medias),
   FOREIGN KEY(id_game) REFERENCES games(id_game)
);

CREATE TABLE to_have(
   id_game INT,
   id_machine INT,
   id_categorie INT,
   PRIMARY KEY(id_game, id_machine, id_categorie),
   FOREIGN KEY(id_game) REFERENCES games(id_game),
   FOREIGN KEY(id_machine) REFERENCES machines(id_machine),
   FOREIGN KEY(id_categorie) REFERENCES categories(id_categorie)
);

CREATE TABLE to_connect(
   id_user INT,
   Id_configuration INT,
   PRIMARY KEY(id_user, Id_configuration),
   FOREIGN KEY(id_user) REFERENCES users(id_user),
   FOREIGN KEY(Id_configuration) REFERENCES configuration(Id_configuration)
);


-- Countries
INSERT INTO countries (country_name, country_code) VALUES
    ('Afghanistan', 'AF'),
    ('Afrique du Sud', 'ZA'),
    ('Åland, Îles', 'AX'),
    ('Albanie', 'AL'),
    ('Algérie', 'DZ'),
    ('Allemagne', 'DE'),
    ('Allemagne de l''EST', 'DD'),
    ('Andorre', 'AD'),
    ('Angola', 'AO'),
    ('Anguilla', 'AI'),
    ('Antarctique', 'AQ'),
    ('Antigua et Barbuda', 'AG'),
    ('Antilles néerlandaises', 'AN'),
    ('Arabie Saoudite', 'SA'),
    ('Argentine', 'AR'),
    ('Arménie', 'AM'),
    ('Aruba', 'AW'),
    ('Australie', 'AU'),
    ('Autriche', 'AT'),
    ('Azerbaïdjan', 'AZ'),
    ('Bahamas', 'BS'),
    ('Bahrein', 'BH'),
    ('Bangladesh', 'BD'),
    ('Barbade', 'BB'),
    ('Bélarus', 'BY'),
    ('Belgique', 'BE'),
    ('Bélize', 'BZ'),
    ('Bénin', 'BJ'),
    ('Bermudes', 'BM'),
    ('Bhoutan', 'BT'),
    ('Bolivie (État plurinational de)', 'BO'),
    ('Bonaire, Saint-Eustache et Saba', 'BQ'),
    ('Bosnie-Herzégovine', 'BA'),
    ('Botswana', 'BW'),
    ('Bouvet, Ile', 'BV'),
    ('Brésil', 'BR'),
    ('Brunéi Darussalam', 'BN'),
    ('Bulgarie', 'BG'),
    ('Burkina Faso', 'BF'),
    ('Burundi', 'BI'),
    ('Cabo Verde', 'CV'),
    ('Caïmans, Iles', 'KY'),
    ('Cambodge', 'KH'),
    ('Cameroun', 'CM'),
    ('Canada', 'CA'),
    ('Chili', 'CL'),
    ('Chine', 'CN'),
    ('Christmas, île', 'CX'),
    ('Chypre', 'CY'),
    ('Cocos/Keeling (Îles)', 'CC'),
    ('Colombie', 'CO'),
    ('Comores', 'KM'),
    ('Congo', 'CG'),
    ('Congo, République démocratique du', 'CD'),
    ('Cook, Iles', 'CK'),
    ('Corée, République de', 'KR'),
    ('Corée, République populaire démocratique de', 'KP'),
    ('Costa Rica', 'CR'),
    ('Côte d''Ivoire', 'CI'),
    ('Croatie', 'HR'),
    ('Cuba', 'CU'),
    ('Curaçao', 'CW'),
    ('Danemark', 'DK'),
    ('Djibouti', 'DJ'),
    ('Dominicaine, République', 'DO'),
    ('Dominique', 'DM'),
    ('Egypte', 'EG'),
    ('El Salvador', 'SV'),
    ('Emirats arabes unis', 'AE'),
    ('Equateur', 'EC'),
    ('Erythrée', 'ER'),
    ('Espagne', 'ES'),
    ('Estonie', 'EE'),
    ('Etats-Unis d''Amérique', 'US'),
    ('Ethiopie', 'ET'),
    ('Falkland/Malouines (Îles)', 'FK'),
    ('Féroé, îles', 'FO'),
    ('Fidji', 'FJ'),
    ('Finlande', 'FI'),
    ('France', 'FR'),
    ('Gabon', 'GA'),
    ('Gambie', 'GM'),
    ('Géorgie', 'GE'),
    ('Géorgie du sud et les îles Sandwich du sud', 'GS'),
    ('Ghana', 'GH'),
    ('Gibraltar', 'GI'),
    ('Grèce', 'GR'),
    ('Grenade', 'GD'),
    ('Groenland', 'GL'),
    ('Guadeloupe', 'GP'),
    ('Guam', 'GU'),
    ('Guatemala', 'GT'),
    ('Guernesey', 'GG'),
    ('Guinée', 'GN'),
    ('Guinée-Bissau', 'GW'),
    ('Guinée équatoriale', 'GQ'),
    ('Guyana', 'GY'),
    ('Guyane française', 'GF'),
    ('Haïti', 'HT'),
    ('Heard, Ile et MacDonald, îles', 'HM'),
    ('Honduras', 'HN'),
    ('Hong Kong', 'HK'),
    ('Hongrie', 'HU'),
    ('Île de Man', 'IM'),
    ('Îles mineures éloignées des Etats-Unis', 'UM'),
    ('Îles vierges britanniques', 'VG'),
    ('Îles vierges des Etats-Unis', 'VI'),
    ('Inde', 'IN'),
    ('Indien (Territoire britannique de l''océan)', 'IO'),
    ('Indonésie', 'ID'),
    ('Iran, République islamique d''', 'IR'),
    ('Iraq', 'IQ'),
    ('Irlande', 'IE'),
    ('Islande', 'IS'),
    ('Israël', 'IL'),
    ('Italie', 'IT'),
    ('Jamaïque', 'JM'),
    ('Japon', 'JP'),
    ('Jersey', 'JE'),
    ('Jordanie', 'JO'),
    ('Kazakhstan', 'KZ'),
    ('Kenya', 'KE'),
    ('Kirghizistan', 'KG'),
    ('Kiribati', 'KI'),
    ('Koweït', 'KW'),
    ('Lao, République démocratique populaire', 'LA'),
    ('Lesotho', 'LS'),
    ('Lettonie', 'LV'),
    ('Liban', 'LB'),
    ('Libéria', 'LR'),
    ('Libye', 'LY'),
    ('Liechtenstein', 'LI'),
    ('Lituanie', 'LT'),
    ('Luxembourg', 'LU'),
    ('Macao', 'MO'),
    ('Macédoine, l''ex-République yougoslave de', 'MK'),
    ('Madagascar', 'MG'),
    ('Malaisie', 'MY'),
    ('Malawi', 'MW'),
    ('Maldives', 'MV'),
    ('Mali', 'ML'),
    ('Malte', 'MT'),
    ('Mariannes du nord, Iles', 'MP'),
    ('Maroc', 'MA'),
    ('Marshall, Iles', 'MH'),
    ('Martinique', 'MQ'),
    ('Maurice', 'MU'),
    ('Mauritanie', 'MR'),
    ('Mayotte', 'YT'),
    ('Mexique', 'MX'),
    ('Micronésie, Etats Fédérés de', 'FM'),
    ('Moldova, République de', 'MD'),
    ('Monaco', 'MC'),
    ('Mongolie', 'MN'),
    ('Monténégro', 'ME'),
    ('Montserrat', 'MS'),
    ('Mozambique', 'MZ'),
    ('Myanmar', 'MM'),
    ('Namibie', 'NA'),
    ('Nauru', 'NR'),
    ('Népal', 'NP'),
    ('Nicaragua', 'NI'),
    ('Niger', 'NE'),
    ('Nigéria', 'NG'),
    ('Niue', 'NU'),
    ('Norfolk, Ile', 'NF'),
    ('Norvège', 'NO'),
    ('Nouvelle-Calédonie', 'NC'),
    ('Nouvelle-Zélande', 'NZ'),
    ('Oman', 'OM'),
    ('Ouganda', 'UG'),
    ('Ouzbékistan', 'UZ'),
    ('Pakistan', 'PK'),
    ('Palaos', 'PW'),
    ('Palestine, Etat de', 'PS'),
    ('Panama', 'PA'),
    ('Papouasie-Nouvelle-Guinée', 'PG'),
    ('Paraguay', 'PY'),
    ('Pays-Bas', 'NL'),
    ('Pays inconnu', 'XX'),
    ('Pays multiples', 'ZZ'),
    ('Pérou', 'PE'),
    ('Philippines', 'PH'),
    ('Pitcairn', 'PN'),
    ('Pologne', 'PL'),
    ('Polynésie française', 'PF'),
    ('Porto Rico', 'PR'),
    ('Portugal', 'PT'),
    ('Qatar', 'QA'),
    ('République arabe syrienne', 'SY'),
    ('République centrafricaine', 'CF'),
    ('Réunion', 'RE'),
    ('Roumanie', 'RO'),
    ('Royaume-Uni de Grande-Bretagne et d''Irlande du Nord', 'GB'),
    ('Russie, Fédération de', 'RU'),
    ('Rwanda', 'RW'),
    ('Sahara occidental', 'EH'),
    ('Saint-Barthélemy', 'BL'),
    ('Saint-Kitts-et-Nevis', 'KN'),
    ('Saint-Marin', 'SM'),
    ('Saint-Martin (partie française)', 'MF'),
    ('Saint-Martin (partie néerlandaise)', 'SX'),
    ('Saint-Pierre-et-Miquelon', 'PM'),
    ('Saint-Siège', 'VA'),
    ('Saint-Vincent-et-les-Grenadines', 'VC'),
    ('Sainte-Hélène, Ascension et Tristan da Cunha', 'SH'),
    ('Sainte-Lucie', 'LC'),
    ('Salomon, Iles', 'SB'),
    ('Samoa', 'WS'),
    ('Samoa américaines', 'AS'),
    ('Sao Tomé-et-Principe', 'ST'),
    ('Sénégal', 'SN'),
    ('Serbie', 'RS'),
    ('Seychelles', 'SC'),
    ('Sierra Leone', 'SL'),
    ('Singapour', 'SG'),
    ('Slovaquie', 'SK'),
    ('Slovénie', 'SI'),
    ('Somalie', 'SO'),
    ('Soudan', 'SD'),
    ('Soudan du Sud', 'SS'),
    ('Sri Lanka', 'LK'),
    ('Suède', 'SE'),
    ('Suisse', 'CH'),
    ('Suriname', 'SR'),
    ('Svalbard et île Jan Mayen', 'SJ'),
    ('Swaziland', 'SZ'),
    ('Tadjikistan', 'TJ'),
    ('Taïwan, Province de Chine', 'TW'),
    ('Tanzanie, République unie de', 'TZ'),
    ('Tchad', 'TD'),
    ('Tchécoslovaquie', 'CS'),
    ('Tchèque, République', 'CZ'),
    ('Terres australes françaises', 'TF'),
    ('Thaïlande', 'TH'),
    ('Timor-Leste', 'TL'),
    ('Togo', 'TG'),
    ('Tokelau', 'TK'),
    ('Tonga', 'TO'),
    ('Trinité-et-Tobago', 'TT'),
    ('Tunisie', 'TN'),
    ('Turkménistan', 'TM'),
    ('Turks-et-Caïcos (Îles)', 'TC'),
    ('Turquie', 'TR'),
    ('Tuvalu', 'TV'),
    ('Ukraine', 'UA'),
    ('URSS', 'SU'),
    ('Uruguay', 'UY'),
    ('Vanuatu', 'VU'),
    ('Vatican : voir Saint-Siège', 'VA'),
    ('Venezuela (République bolivarienne du)', 'VE'),
    ('Viet Nam', 'VN'),
    ('Viet Nam (Sud)', 'VD'),
    ('Wallis et Futuna', 'WF'),
    ('Yémen', 'YE'),
    ('Yougoslavie', 'YU'),
    ('Zaïre', 'ZR'),
    ('Zambie', 'ZM'),
    ('Zimbabwe', 'ZW');

-- Users
-- mot de pass : passPASS14-

INSERT INTO users (user_nikename, user_birthdate, user_email, user_signin_date, user_password_hash) VALUES
('Zisquier', '1977-06-28', 'tbressel.dev@gmail.com', '2023-11-01 11:11:11','$2y$10$uyWDTkO8Yoyhc5XVWVEDke3yfUyY07SvF0LVhN3lKAnbH9zzVN76C'),
('Amstariga', '1987-04-18', 'amsta@email.com', '2023-11-02 12:12:12','$2y$10$uyWDTkO8Yoyhc5XVWVEDke3yfUyY07SvF0LVhN3lKAnbH9zzVN76C'),
('Tbressel', '1999-11-02', 'tbressel@email.com', '2023-11-03 13:13:13','$2y$10$uyWDTkO8Yoyhc5XVWVEDke3yfUyY07SvF0LVhN3lKAnbH9zzVN76C'),
('Wisauier', '1996-07-15', 'wisauier@email.com', '2023-11-04 14:14:14','$2y$10$uyWDTkO8Yoyhc5XVWVEDke3yfUyY07SvF0LVhN3lKAnbH9zzVN76C');

-- Manufacturers
INSERT INTO manufacturers (manufacturer_name) VALUES
    ('Atari'),
    ('Commodore'),
    ('Sinclair Research'),
    ('Amstrad'),
    ('Texas Instruments'),
    ('Coleco'),
    ('Mattel Electronics'),
    ('Emerson Radio'),
    ('Magnavox'),
    ('Fairchild Semiconductor'),
    ('RCA'),
    ('Nintendo'),
    ('Sega'),
    ('Sony'),
    ('NEC'),
    ('SNK'),
    ('Acorn Computers'),
    ('Apple Inc.'),
    ('Bally Technologies'),
    ('Bandai'),
    ('Capcom'),
    ('Cisco'),
    ('Epyx'),
    ('Tiger Electronics'),
    ('Casio'),
    ('Epoch'),
    ('Fujitsu'),
    ('Sharp'),
    ('Famicom'),
    ('NEC Avenue'),
    ('HAL Laboratory'),
    ('Enix'),
    ('Sun Electronics'),
    ('Epoch Co.'),
    ('Bit Corporation'),
    ('Daewoo'),
    ('VTech'),
    ('Spectravideo'),
    ('CreatiVision'),
    ('Hanimex'),
    ('Radofin'),
    ('Videopac'),
    ('APF Electronics'),
    ('CGL'),
    ('Sheen'),
    ('Microsoft'),
    ('Xbox Game Studios'),
    ('Sega Sammy Holdings'),
    ('Sony Interactive Entertainment'),
    ('Nintendo'),
    ('Google'),
    ('Valve Corporation'),
    ('Oculus VR'),
    ('Amazon'),
    ('Razer Inc.'),
    ('Nvidia'),
    ('Mad Catz'),
    ('Logitech'),
    ('Hyperkin'),
    ('Hori'),
    ('8Bitdo'),
    ('Anki'),
    ('Apple Inc.'),
    ('Intellivision Entertainment'),
    ('Playdate'),
    ('Anbernic'),
    ('Evercade'),
    ('Polymega');

-- Machines
INSERT INTO machines (machine_model, machine_releasedate, machine_label_picture, id_manufacturer) VALUES
    ('CPC 6128', '1984-01', 'img/plateforms/webp/amstrad-cpc.webp',4), 
    ('STe 1040', '1985-04', 'img/plateforms/webp/atari-st.webp',1), 
    ('Playstation 4', '2013-07', 'img/plateforms/webp/sony-playstation4.webp',14), 
    ('Switch (classic)', '2017-03', 'img/plateforms/webp/nintendo-switch.webp',12), 
    ('Super Nintendo (EU)', '1992-07', 'img/plateforms/webp/nintendo-supernintendo.webp',12), 
    ('Master System (EU)', '1987-07', 'img/plateforms/webp/sega-megadrive.webp',13), 
    ('PC Windows', '1985-07', 'img/plateforms/webp/microsoft-windows.webp',46),
    ('Amiga 500', '1987-07', 'img/plateforms/webp/commodore-amiga500.webp',2), 
    ('Mega Drive (EU)', '1992-07', 'img/plateforms/webp/sega-megadrive.webp',13), 
    ('Game Boy (EU)', '1989-07', 'img/plateforms/webp/nintendo-gameboy.webp',12), 
    ('NES (EU)', '1985-07', 'img/plateforms/webp/nintendo-nes.webp',12), 
    ('ZX Spectrum', '1982-07', 'img/plateforms/webp/sinclair-zx-spectrum.webp',3), 
    ('Commodore 64', '1982-07', 'img/plateforms/webp/commodore-64.webp',2), 
    ('Apple II', '1977-07', 'img/plateforms/webp/apple-ii.webp',63),
    ('2600', '1977-09', 'img/plateforms/webp/atari-2600.webp',1), 
    ('Intellivision', '1979-09', 'img/plateforms/webp/intellivision.webp',7 ), 
    ('ColecoVision', '1982-08', 'img/plateforms/webp/colecovision.webp', 6), 
    ('N64', '1996-06', 'img/plateforms/webp/nintendo-64.webp',12), 
    ('GameCube', '2001-09', 'img/plateforms/webp/nintendo-gamecube.webp',12), 
    ('Wii', '2006-11', 'img/plateforms/webp/nintendo-wii.webp',12), 
    ('Saturn', '1994-02', 'img/plateforms/webp/sega-saturn.webp',13), 
    ('PlayStation', '1994-12', 'img/plateforms/webp/sony-playstation.webp',14), 
    ('PlayStation 2', '2000-03', 'img/plateforms/webp/sony-playstation2.webp',14), 
    ('PlayStation 3', '2006-11', 'img/plateforms/webp/sony-playstation3.webp',14), 
    ('PlayStation 5', '2013-07', 'img/plateforms/webp/sony-playstation4.webp',14), 
    ('Xbox', '2001-11', 'img/plateforms/webp/microsoft-xbox.webp', 46), 
    ('Xbox 360', '2005-11', 'img/plateforms/webp/microsoft-xbox360.webp', 46), 
    ('Xbox One', '2013-11', 'img/plateforms/webp/microsoft-xboxone.webp',46 );

-- Dates
INSERT INTO dates (date_year) VALUES
    -- 1 à 3
    (1977), (1978), (1979),
    -- 4 à 12
    (1980), (1981), (1982), (1983), (1984), (1985), (1986),
    (1987), (1988), (1989),
    -- 13 à 22
     (1990), (1991), (1992), (1993), (1994), (1995), (1996),
    (1997), (1998), (1999),
    -- 23 à 32
     (2000), (2001), (2002), (2003), (2004), (2005), (2006),
    (2007), (2008), (2009),
    -- 33 à 42
     (2010), (2011), (2012), (2013), (2014), (2015), (2016),
    (2017), (2018), (2019),
    -- 43 à 46
     (2020), (2021), (2022), (2023),(2024), (2025);

-- Editors
INSERT INTO editors (editor_name, id_country) VALUES
    ('07th Expansion', 118),
    ('11 bit studios', 185),
    ('1C Company', 195),
    ('1492 Studio', 80),
    ('2K Games', 74),
    ('2K Play', 74),
    ('2K Sports', 74),
    ('21st Century Entertainment', 194),
    ('3D Realms', 74),
    ('3DO Company, The', 74),
    ('505 Games', 116),
    ('5pb.', 118),
    ('7th Level', 18),
    ('989 Studios', 74),
    ('Aackosoft', 179),
    ('ABC Software', 74),
    ('Absolute Entertainment', 74),
    ('Access Software', 74),
    ('Acclaim Entertainment', 74),
    ('Accolade', 74),
    ('Acornsoft', 194),
    ('Acquire', 118),
    ('Active Gaming Media', 118),
    ('Activision', 74),
    ('Activision Blizzard', 74),
    ('Addictive Games', 194),
    ('ADK', 118),
    ('Adult Swim Games', 74),
    ('Adventure Company, The', 74),
    ('Adventure International', 74),
    ('Adventure Soft', 194),
    ('Aeria Games', 74),
    ('Affect', 118),
    ('Ageod', 80),
    ('Agetec', 74),
    ('Akella', 195),
    ('Aksys Games', 74),
    ('Alawar Entertainment', 195),
    ('Alchemist', 118),
    ('AliceSoft', 118),
    ('AlphaDream', 118),
    ('Alphapolis', 118),
    ('Alternative Software', 194),
    ('Altron', 118),
    ('Ambrosia Software', 74),
    ('American Game Cartridges', 74),
    ('American Laser Games', 74),
    ('AMI', 74),
    ('Amiga', 74),
    ('Amplitude Studios', 80),
    ('Amsoft', 194),
    ('Anco', 194),
    ('Andamiro', 56),
    ('Animoca', 102),
    ('Ankama Games', 80),
    ('Annapurna Interactive', 74),
    ('Anuman Interactive', 80),
    ('Apogee Software', 74),
    ('AQ Interactive', 118),
    ('Aquaplus', 118),
    ('Arc System Works', 118),
    ('ARG Informatique', 80),
    ('Arika', 118),
    ('Armor Games', 74),
    ('Arush Entertainment', 74),
    ('ASC Games', 74),
    ('Ascaron Entertainment', 6),
    ('ASCII', 118),
    ('Asmik Ace Entertainment', 118),
    ('Aspyr', 74),
    ('Asymmetric Publications', 74),
    ('Atari', 74),
    ('Atari Corporation', 74),
    ('Atari Games', 74),
    ('Atari Inc.', 74),
    ('Atari Inc.', 74),
    ('Atari Interactive', 74),
    ('Atari SA', 80),
    ('Athena', 118),
    ('Atlantis Interactive Entertainment', 194),
    ('Atlus', 118),
    ('Attic Entertainment Software', 6),
    ('Automated Simulations', 74),
    ('Avalon Hill', 74),
    ('Aztech New Media', 194),
    ('Bally Midway Manufacturing Company', 74),
    ('Bam! Entertainment', 74),
    ('Bandai', 118),
    ('Bandai Namco Entertainment', 118),
    ('Banpresto', 118),
    ('Battlefront.com', 74),
    ('BBC Multimedia', 194),
    ('Bethesda Softworks', 74),
    ('BHV Software', 80),
    ('Bigben Interactive', 80),
    ('Bigpoint', 6),
    ('Bishop', 74),
    ('BitRabbit', 229),
    ('Black Bean Games', 116),
    ('Black Pearl Software', 74),
    ('Blackstar Interactive', 74),
    ('Bleu-ciel informatique', 80),
    ('Blizzard Entertainment', 74),
    ('Blue Byte', 6),
    ('Blue Mammoth Games', 74),
    ('Blue Planet Software', 74),
    ('BMG Interactive', 74),
    ('Bohemia Interactive', 233),
    ('Bonnier Multimedia', 223),
    ('Bottom Up', 118),
    ('Brøderbund Software', 74),
    ('Buena Vista Games', 74),
    ('Buka Entertainment', 195),
    ('Bulkypix', 80),
    ('Bullet-Proof Software', 74),
    ('Bungie Studios', 74),
    ('Bushiroad', 118),
    ('C&E', 118),
    ('Cs Ware', 118),
    ('Camelot Software Planning', 118),
    ('Capcom', 118),
    ('Carrere Video', 80),
    ('Casio', 118),
    ('Cave', 118),
    ('CD Projekt', 185),
    ('CDV Software Entertainment', 6),
    ('Ceaco', 74),
    ('Cenega', 233),
    ('Chunsoft', 118),
    ('City Interactive', 185),
    ('Claris Corporation', 74),
    ('Climax Entertainment', 118),
    ('Codemasters', 194),
    ('Coffee Stain Studios', 223),
    ('Coleco', 74),
    ('Color Dreams', 74),
    ('CommaVid', 74),
    ('Compile', 118),
    ('Compulsion Games', 45),
    ('Conspiracy Entertainment', 74),
    ('Core Design Ltd.', 194),
    ('Coreland', 118),
    ('Crave Entertainment', 74),
    ('Creative Computing', 74),
    ('Cryo Interactive', 80),
    ('Cultures AG', 6),
    ('Culture Brain', 118),
    ('Cyberdreams', 74),
    ('CyberFront', 118),
    ('D3 Publisher', 118),
    ('D4 Enterprise', 118),
    ('Daedalic Entertainment', 6),
    ('Daito', 118),
    ('Data Age', 74),
    ('Data East', 118),
    ('Datam Polystar', 118),
    ('Datamet', 74),
    ('Datamost', 74),
    ('Daybreak Game Company', 74),
    ('DC Studios', 194),
    ('Dempa', 118),
    ('Destination Software, Inc.', 74),
    ('Detn8 Games', 74),
    ('Devolver Digital', 74),
    ('DigiCube', 118),
    ('Digital Bros.', 116),
    ('Digital Eclipse', 74),
    ('Digital Extremes', 45),
    ('Digital Leisure', 45),
    ('Disney Interactive Studios', 74),
    ('Dixons Retail', 194),
    ('Dorart', 118),
    ('Dorasu', 118),
    ('DTP Entertainment', 6),
    ('Dusenberry Martin Racing', 74),
    ('Dynamix', 74),
    ('Ecole', 118),
    ('Ecole Software', 118),
    ('Edia', 118),
    ('Ediciones Sirio', 72),
    ('Edusoft', 74),
    ('Eidos Interactive', 194),
    ('Eidetic', 74),
    ('Electronic Arts', 74),
    ('Electronic Arts Victor', 118),
    ('Electronic Arts Square', 118),
    ('Elite', 194),
    ('Epic Games', 74),
    ('Epoch', 118),
    ('Ertain', 118),
    ('Este', 118),
    ('Evolution Games', 74),
    ('Evolutionary Publishing', 74),
    ('Examu', 118),
    ('Excalibur Publishing', 194),
    ('Exception', 118),
    ('Exertainment', 74),
    ('Extreme Entertainment Group', 74),
    ('Extreme Entertainment Group', 74),
    ('Falcom', 118),
    ('Family Soft', 118),
    ('Fanfare', 118),
    ('FanPro', 6),
    ('Fantasy Flight Games', 74),
    ('Fillpoint', 74),
    ('Firebird', 194),
    ('Firefly Studios', 194),
    ('First Star Software', 74),
    ('Flashpoint Games', 194),
    ('Flight-Plan', 118),
    ('Focus Home Interactive', 80),
    ('Focus Multimedia', 194),
    ('fonfun', 229),
    ('Foreign Media Games', 74),
    ('Four Winds Fantasy Gaming', 74),
    ('Fox Interactive', 74),
    ('Freebird Games', 45),
    ('Frontier Developments', 194),
    ('Fuji', 118),
    ('FuRyu', 118),
    ('Future Publishing', 194),
    ('G.rev', 118),
    ('Gainax Network Systems', 118),
    ('Gakken', 118),
    ('Game Arts', 118),
    ('Game Factory', 74),
    ('Game Life', 118),
    ('GameMill Entertainment', 74),
    ('GameTek', 74),
    ('Gathering, The', 74),
    ('General Entertainment', 118),
    ('General Entertainment', 118),
    ('Genki', 118),
    ('Genterprise', 118),
    ('Ghostlight', 194),
    ('Giga', 118),
    ('GIGA', 118),
    ('Global A Entertainment', 118),
    ('Gotham Games', 74),
    ('Graffiti', 118),
    ('Grand Prix Games', 74),
    ('Grandream', 194),
    ('Graphsim Entertainment', 74),
    ('Gremlin Interactive Ltd', 194),
    ('Griffin International', 74),
    ('Groove Games', 45),
    ('GT Interactive', 74),
    ('GungHo', 118),
    ('Gust', 118),
    ('H2 Interactive', 56),
    ('Hackberry', 118),
    ('Hal America', 118),
    ('HAL Laboratory', 118),
    ('Hamster Corporation', 118),
    ('Happinet', 118),
    ('Hasbro Interactive', 74),
    ('Havas Interactive', 74),
    ('Heart Soft', 118),
    ('Hi Tech Expressions', 74),
    ('HMH Interactive', 6),
    ('Home Entertainment Suppliers', 18),
    ('Home Vision', 74),
    ('Hori', 118),
    ('Hudson Entertainment', 74),
    ('Hudson Soft', 118),
    ('Human Entertainment', 118),
    ('HuneX', 118),
    ('I Max', 118),
    ('IBM', 74),
    ('Iceberg Interactive', 179),
    ('Idea Factory', 118),
    ('IE Institute', 118),
    ('Idea Factory International', 74),
    ('Ignition Entertainment', 74),
    ('Igs', 229),
    ('Illusion Softworks', 233),
    ('Imadio', 74),
    ('Image Epoch', 118),
    ('Imagic', 74),
    ('Imagineer', 118),
    ('IMGN.PRO', 185),
    ('Inc.', 118),
    ('indiePub', 74),
    ('IndieBuilt', 74),
    ('Infocom', 74),
    ('Infogrames', 80),
    ('Insomniac Games', 74),
    ('Insomniac Games', 74),
    ('Intec', 74),
    ('Intec', 74),
    ('Interchannel', 118),
    ('Interplay', 74),
    ('Interplay Productions', 74),
    ('Interplay Productions', 74),
    ('Interplay Records', 74),
    ('Inti Creates', 118),
    ('Introversion Software', 194),
    ('Irem', 118),
    ('ITT Family Games', 74),
    ('ITT Family Games', 74),
    ('J-Wing', 118),
    ('Jack of All Games', 74),
    ('Jaleco', 118),
    ('Jaleco', 74),
    ('118 Home Video', 118),
    ('Jorudan', 118),
    ('Kaga Create', 118),
    ('Kadokawa Games', 118),
    ('Kadokawa Shoten', 118),
    ('Kaga Tech', 118),
    ('Kamui', 118),
    ('Kaneko', 118),
    ('Kando Games', 74),
    ('Karin Entertainment', 118),
    ('Kemco', 118),
    ('Kemco', 118),
    ('KID', 118),
    ('Kiki Trick', 118),
    ('Klei Entertainment', 45),
    ('Knowledge Adventure', 74),
    ('Koch Media', 6),
    ('Koei', 118),
    ('Koei Tecmo Games', 118),
    ('Konami', 118),
    ('Kool Kizz', 74),
    ('Kotobuki System', 118),
    ('KSS', 118),
    ('Laguna', 118),
    ('Laguna', 118),
    ('Laguna', 118),
    ('Langmaor', 118),
    ('LaserSoft', 118),
    ('Last Day of Work', 74),
    ('Legacy Interactive', 74),
    ('Legend Entertainment Company', 74),
    ('Lego Interactive', 63),
    ('Leland Corporation', 74),
    ('Lemon Interactive', 80),
    ('Level-5', 118),
    ('Lexis Numérique', 80),
    ('Lighthouse Interactive', 179),
    ('Linden Lab', 74),
    ('LJN', 74),
    ('Llamasoft', 194),
    ('Loriciel', 80),
    ('LucasArts', 74),
    ('M. C. Lothlorien', 118),
    ('MacPlay', 74),
    ('MacSoft Games', 74),
    ('Madfinger Games', 233),
    ('Magical Company', 118),
    ('Majesco Entertainment', 74),
    ('Malfador Machinations', 74),
    ('MangaGamer', 74),
    ('Marvel Games', 74),
    ('Marvelous', 118),
    ('Marvelous Entertainment', 118),
    ('Marvelous USA', 74),
    ('Matrix Games', 74),
    ('Masaya', 118),
    ('Mastertronic', 194),
    ('Mattel Electronics', 74),
    ('Maxis', 74),
    ('MC2 80', 80),
    ('Melbourne House', 18),
    ('Meridian4', 74),
    ('Merscom', 74),
    ('Metro3D', 74),
    ('MGM Interactive', 74),
    ('Mi-Clos Studio', 80),
    ('Micro Application', 80),
    ('Microfolie''s', 80),
    ('Microids', 80),
    ('Micronet co., Ltd.', 118),
    ('MicroProse', 74),
    ('Microsoft', 74),
    ('Midas Interactive Entertainment', 194),
    ('Midway Games', 74),
    ('Mikengreg', 74),
    ('Milestone Interactive', 116),
    ('Millennium Interactive', 194),
    ('Milton Bradley Company', 74),
    ('Mindscape', 74),
    ('Mirrorsoft', 194),
    ('Mitchell Corporation', 118),
    ('Mojang', 223),
    ('Molleindustria', 116),
    ('Monolith Productions', 74),
    ('Monte Cristo Multimedia', 80),
    ('Montparnasse Multimedia', 80),
    ('Moonstone', 194),
    ('MOSS', 118),
    ('Motion Twin', 80),
    ('MTO', 118),
    ('MTV Games', 74),
    ('Muse Software', 74),
    ('Mystique', 74),
    ('Namco', 118),
    ('Natsume', 118),
    ('Navel', 118),
    ('Navigo', 118),
    ('NBCUniversal Entertainment 118', 118),
    ('NCS Corporation', 118),
    ('NCsoft', 56),
    ('Neko Entertainment', 80),
    ('NeocoreGames', 103),
    ('Neowiz Games', 56),
    ('New World Computing', 74),
    ('Nexon', 56),
    ('ngmoco', 74),
    ('Niantic', 74),
    ('Nicalis', 74),
    ('Nightdive Studios', 74),
    ('Nihon Bussan', 118),
    ('Nihon Falcom', 118),
    ('Nihon System', 118),
    ('Nihon Telenet', 118),
    ('Nintendo', 118),
    ('Nippon Amuse', 118),
    ('Nippon Columbia', 118),
    ('Nippon Ichi Software', 118),
    ('Nirvana Systems', 74),
    ('NIS America', 74),
    ('Nitroplus', 118),
    ('Nival', 195),
    ('Nordcurrent', 133),
    ('Nordic Games Publishing', 19),
    ('Noumenon Games', 74),
    ('NovaLogic', 74),
    ('Now Production', 118),
    ('NTVIC', 118),
    ('O3 Entertainment', 74),
    ('Ocean Software', 194),
    ('Octagon Entertainment', 74),
    ('Octopus Tree', 74),
    ('On Games', 116),
    ('On Hand Software', 74),
    ('Onan Games', 74),
    ('Origin Systems', 74),
    ('Outspark', 74),
    ('Oxygen Interactive', 194),
    ('P2 Games', 194),
    ('Pack-In-Video', 118),
    ('Palcom', 118),
    ('Palgrave Macmillan', 194),
    ('Panther Games', 18),
    ('Panther Software', 194),
    ('Paon Corporation', 118),
    ('PaRappa the Rapper', 118),
    ('Paradox Interactive', 223),
    ('Parker Brothers', 74),
    ('Phoenix Games', 194),
    ('PinkLime Games', 74),
    ('PixelStorm Entertainment Studios', 74),
    ('Pivotal Games', 194),
    ('Playscape', 74),
    ('Playtonic Games', 194),
    ('Pony Canyon', 118),
    ('PopCap Games', 74),
    ('PopTop Software', 74),
    ('Portable Zoo', 118),
    ('Project Two Interactive', 179),
    ('Psygnosis', 194),
    ('Pulse Entertainment', 74),
    ('Quest Corporation', 118),
    ('Quintet', 118),
    ('Quixel', 223),
    ('Rage Software', 194),
    ('Rainbird Software', 194),
    ('Rainy Frog', 118),
    ('Ratalaika Games', 72),
    ('Raw Fury', 223),
    ('Rebellion', 194),
    ('Red Candle Games', 229),
    ('Red Orb Entertainment', 74),
    ('RedOctane', 74),
    ('RedSpotGames', 6),
    ('Reflexive Entertainment', 74),
    ('Rejet', 118),
    ('Renovation Products', 74),
    ('Rising Star Games', 194),
    ('Riverhillsoft', 118),
    ('Rocket Company', 118),
    ('RocketSnail Games', 45),
    ('Rokumendo', 118),
    ('Russel', 118),
    ('Sachen', 229),
    ('Sacnoth', 118),
    ('Sammy Corporation', 118),
    ('Sears', 74),
    ('SEGA', 118),
    ('Senile Team', 74),
    ('Seta Corporation', 118),
    ('SGE', 118),
    ('Shoei System', 118),
    ('Shogakukan Production', 118),
    ('Shogakukan', 118),
    ('Sierra On-Line', 74),
    ('Sigma Team Inc.', 195),
    ('Simogo', 223),
    ('Sir-Tech Software', 45),
    ('Slitherine Software', 194),
    ('SNK', 118),
    ('Societa', 118),
    ('Sodium 24H', 118),
    ('Soft Pro International', 118),
    ('Softdisk Publishing', 74),
    ('Softmax', 56),
    ('Softside', 74),
    ('Sony Computer Entertainment', 118),
    ('Sony Computer Entertainment America', 74),
    ('Sony Computer Entertainment Europe', 194),
    ('Sony Interactive Entertainment', 74),
    ('Soul and Vibe Interactive', 74),
    ('SouthPeak Games', 74),
    ('Spectravision', 74),
    ('Spike', 118),
    ('Square', 118),
    ('Square Enix', 118),
    ('SSI', 74),
    ('Stainless Games', 194),
    ('Starpath Corporation', 74),
    ('Sting', 118),
    ('Storm City Games', 74),
    ('Strategy First', 45),
    ('Studio Drydock', 74),
    ('Studio e.go!', 118),
    ('Studio Saizensen', 118),
    ('Subdued Software', 74),
    ('Sudden Impact', 74),
    ('Sunflowers', 6),
    ('Sunrise Interactive', 118),
    ('Sunsoft', 118),
    ('Super Fighter Team', 74),
    ('Super.com', 74),
    ('Supreme', 118),
    ('Supreme Entertainment', 118),
    ('Swing! Entertainment', 6),
    ('Sydney Development', 18),
    ('System 3', 194),
    ('System Sacom', 118),
    ('T&E Soft', 118),
    ('Taito', 118),
    ('Take-Two Interactive', 74),
    ('Takuyo', 118),
    ('Talbot', 118),
    ('TalonSoft', 74),
    ('Taniko', 118),
    ('TecMagik', 74),
    ('TechnoSoft', 118),
    ('Tehkan', 118),
    ('Telarium', 74),
    ('Telegames', 74),
    ('Telenet 118', 118),
    ('Telstar', 74),
    ('Telstar Fun & Games', 74),
    ('THQ', 74),
    ('THQ Nordic', 19),
    ('Time Warner Interactive', 74),
    ('Titus', 80),
    ('Toaplan', 118),
    ('Tomy Corporation', 118),
    ('Topologika', 194),
    ('TopWare Interactive', 6),
    ('Torus Games', 18),
    ('Touchstone', 74),
    ('Tradewest', 74),
    ('Traveller''s Tales', 194),
    ('Treco', 118),
    ('Tri Synergy', 74),
    ('Triangle Service', 118),
    ('Trion Worlds', 74),
    ('Tripwire Interactive', 74),
    ('Tru Blu Entertainment', 18),
    ('Ubisoft', 80),
    ('UFO Interactive Games', 74),
    ('UIG Entertainment', 6),
    ('Ultravision', 74),
    ('Umbrella', 118),
    ('Unbalance', 118),
    ('Unico Electronics', 118),
    ('United Independent Entertainment', 6),
    ('Universal Gamex', 118),
    ('Universal Interactive Studios', 74),
    ('UPL', 118),
    ('Valcon Games', 74),
    ('ValuSoft', 74),
    ('Valve', 74),
    ('VAP', 118),
    ('Vatical Entertainment', 74),
    ('Vic Tokai', 118),
    ('Victor Interactive', 118),
    ('Virgin Interactive', 194),
    ('Viridis', 74),
    ('Virtual Play Games', 74),
    ('Virtuoso', 118),
    ('Visco Corporation', 118),
    ('Viva Media', 74),
    ('Vivid Image', 194),
    ('VM Labs', 74),
    ('Volition', 74),
    ('Vortex', 118),
    ('Vostok Games', 246),
    ('Warashi', 118),
    ('Warner Bros. Interactive Entertainment', 74),
    ('Warp', 118),
    ('WarpSpeed', 74),
    ('WayForward', 74),
    ('Webfoot Technologies', 74),
    ('Westwood Studios', 74),
    ('White Park Bay Software', 194),
    ('Williams Entertainment', 74),
    ('Wizardry Creative Group', 118),
    ('Working Designs', 74),
    ('Worlds Apart Productions', 74),
    ('Wright Flyer Studios', 118),
    ('Xing Entertainment', 118),
    ('XSEED Games', 74),
    ('Xsonic', 118),
    ('Xtreme Games', 74),
    ('Xyrality', 6),
    ('Yacht Club Games', 74),
    ('Yeti', 118),
    ('YMCAT', 118),
    ('Ysbryd Games', 74),
    ('Yudo', 118),
    ('Yuke''s', 118),
    ('Yumedia', 116),
    ('Zap Corporation', 118),
    ('Ziggurat', 72),
    ('Zoo Corporation', 118),
    ('Zuxxez', 6),
    ('ZYX', 118);

-- Games
INSERT INTO games (game_title, game_subtitle, game_reference, game_cover, id_dates, id_editor) VALUES
    ('Barbarian', '', 'FPS789', 'img/covers/cpc-barbarian-cover.jpg', 10, 6),
    ('Double Dragon', '', 'FPS789', 'img/covers/cpc-doubledragon-cover.jpg', 19, 7),
    ('Prehistorik 2', '', 'FPS789', 'img/covers/cpc-prehistorik2-cover.jpg', 16, 2),
    ('Rick Dangerous', '', 'FPS789', 'img/covers/cpc-rickdangerous-cover.jpg', 11, 8),
    ('Goat Simulator', '', 'WOM456', 'img/covers/pc-goatsimulator-cover.jpg', 37, 5),
    ('Grand Theft Auto 5', '', 'FD789', 'img/covers/ps4-grandtheftauto5-cover.jpg', 36, 9),
    ('Mortal Kombat 2', '', 'RPG456', 'img/covers/sms-mortalkombat2-cover.jpg', 13, 10),
    ('Earth Worm Jim 2', '', 'SCB123','img/covers/snes-earthwormjim2-cover.jpg', 15, 4),
    ('Energy Breaker', '', 'MJ789', 'img/covers/snes-energybreaker-cover.jpg', 15, 4),
    ('Mario Kart Delux 8', '', 'MJ789',  'img/covers/switch-mariokartdeluxe8-cover.png', 43, 4),
    ('Splatton 2', '', 'MJ789',  'img/covers/switch-splatoon2-cover.png', 35, 4),
    ('The Legend Of Zelda', 'Breath Of The Wild', 'MJ789', 'img/covers/switch-thelegendofzelda-breathofthewild-cover.png', 42, 4);

-- Categories
INSERT INTO categories (category_name) VALUES
('Combat'),
('Beat em up'),
('Course'),
('Action'),
('Stratégie'),
('RPG'),
('FPS'),
('Simulation'),
('Plateforme');
-- Assossiation catégories / jeux
INSERT INTO to_have (id_game, id_machine, id_categorie) VALUES
(1,  1, 1),
(2,  1, 2),
(3,  1, 9),
(4,  1, 9),
(5,  7, 8),
(5,  7, 4),
(6,  3, 2),
(6,  3, 3),
(6,  3, 4),
(6,  3, 7),
(7,  6, 9),
(8,  5, 9),
(9,  5, 1),
(10, 4, 3),
(11, 4, 4),
(12, 4, 6);



-- Medias
INSERT INTO medias (media_type, media_storage_capacity, media_faces) VALUES
    ('Dématérialisé', '', 0),
    ('DVD', '4.7 Go', 1),
    ('Blu-ray', '25 Go', 1),
    ('Cassette', '15 mn', 2),
    ('Cassette', '25 mn', 2),
    ('Cassette', '35 mn', 2),
    ('Cassette', '45 mn', 2),
    ('Disquette 3"', '256 Ko', 2),
    ('Disquette 3"½ (DD) ', '720 Ko', 2),
    ('Disquette 3"½ (HD) ', '1.44 Mo', 2),
    ("Disquette 5'¼ (SD) ", '160 Ko', 1),
    ("Disquette 5'¼ (DD)", '320 Ko', 2),
    ('Cartouche', '15.3', 0);


INSERT INTO state (copie_state_rank, copie_state_name, copie_state_description) VALUES
('1 / 10' , 'Méconnaissable !', 'red-color'),
('2 / 10' , 'Très mauvais état et très sale !', 'red-color'),
('3 / 10' , 'Très mauvais état', 'red-color'),
('4 / 10' , 'Mauvais état - il a prit cher !', 'red-color'),
('4,5 / 10' , 'Mauvais état - pas catastrophique', 'orange-color'),
('5 / 10', 'Etat moyen - marqué par le temps', 'orange-color'),
('6 / 10' , 'Etat correct - il a pas mal servit', 'orange-color'),
('7 / 10' , 'Assez bon état - ila son age', 'orange-color'),
('8 / 10' , 'Très bon état', 'green-color'),
('9 / 10' , 'Très bon état - comme neuf', 'green-color'),
('9,5 / 10' , 'Neuf sous blister - presque mint', 'green-color'),
('10 / 10' , 'Neuf sous blister - mint', 'green-color');


-- Copie
INSERT INTO copie (copie_price, copie_addition_date, id_user, id_machine, id_medias, id_game, id_state)
VALUES 
( 12.99,  '2023-02-15 20:45:05', 4, 2, 3, 4, 1),
( 36.00,  '2023-03-12 12:30:15', 1, 1, 5, 7, 2),
( 40.50,  '2022-03-25 18:45:30', 1, 1, 4, 2, 2),
( 2.00, '2020-03-02 08:15:00', 2, 1, 2, 6, 3),
( 4.99, '2023-04-17 22:30:45', 4, 2, 2, 5, 4),
( 8.00, '2022-12-05 10:00:20', 3, 3, 5, 7, 3),
( 50.50,  '2022-09-22 15:20:10', 1, 4, 4, 3, 3),
( 120.00, '2023-02-15 23:55:30', 1, 4, 3, 4, 6),
( 12.00,  '2023-03-20 05:40:10', 1, 4, 2, 6, 7),
( 100.99, '2021-06-26 18:10:55', 4, 4, 5, 7, 8),
( 24.50,  '2021-04-28 14:05:40', 4, 4, 5, 7, 9),
( 26.99,  '2001-04-28 14:05:40', 4, 1, 2, 6, 10),
( 32.00,  '2024-04-28 14:05:40', 4, 1, 2, 5, 0),
( 9.50, '2024-06-28 14:05:40', 4, 1, 3, 4, 5),
( 2.00, '2020-03-02 08:15:00', 1, 1, 2, 6, 3),
( 4.99, '2023-04-17 22:30:45', 1, 2, 2, 5, 4),
( 8.00, '2022-12-05 10:00:20', 1, 3, 5, 7, 3);

-- création d'une vue pour générer des statistiques
CREATE VIEW game_statistics AS
SELECT
    id_game,
    game_title,
    AVG(copie_price) AS game_avg_price,
    MIN(copie_price) AS game_min_price,
    MAX(copie_price) AS game_max_price,
    COUNT(id_copie) AS total_copies
FROM
    copie
JOIN
    games USING (id_game)
GROUP BY
    id_game, game_title;


-- consulter la vue
-- SELECT
--     gs.id_game,
--     gs.game_title,
--     gs.game_avg_price,
--     gs.game_min_price,
--     gs.game_max_price,
--     gs.total_copies
-- FROM
--     game_statistics gs
-- JOIN
--     copie c ON gs.id_game = c.id_game
-- WHERE
--     id_user = 1;



SELECT
    c.category_name AS filter_name,
    COUNT(DISTINCT g.id_game) AS total_games,
    COUNT(DISTINCT CASE WHEN co.id_user = 1 THEN g.id_game END) AS games_owned_user
FROM
    categories c
LEFT JOIN
    to_have t USING (id_categorie)
LEFT JOIN
    copie co USING (id_game)
LEFT JOIN
    games g USING (id_game)
GROUP BY
    c.id_categorie, c.category_name;




SELECT
    m.media_type AS filter_name,
    COUNT(DISTINCT g.id_game) AS total_games,
    COUNT(DISTINCT CASE WHEN co.id_user = 1 THEN g.id_game END) AS games_owned_user
FROM
    medias m
LEFT JOIN
    copie co USING (id_medias)
LEFT JOIN
    games g USING (id_game)
GROUP BY
    m.media_type;


CREATE VIEW manufacturer_game_statistics AS
SELECT
    m.manufacturer_name,
    COUNT(DISTINCT th.id_game) AS total_games,
    COUNT(DISTINCT CASE WHEN c.id_user = 1 THEN th.id_game END) AS games_owned_by_user_1
FROM
    manufacturers m
LEFT JOIN
    machines ma ON m.id_manufacturer = ma.id_manufacturer
LEFT JOIN
    to_have th ON ma.id_machine = th.id_machine
LEFT JOIN
    copie c ON th.id_game = c.id_game AND c.id_user = 1
GROUP BY
    m.manufacturer_name
ORDER BY
    m.manufacturer_name;




SELECT
    m.machine_model AS filter_name,
    COUNT(DISTINCT g.id_game) AS total_games,
    COUNT(DISTINCT CASE WHEN co.id_user = 1 THEN g.id_game END) AS games_owned_user
FROM
    machines m
LEFT JOIN
    to_have t USING (id_machine)
LEFT JOIN
    games g USING (id_game)
LEFT JOIN
    copie co ON g.id_game = co.id_game AND co.id_user = 1
GROUP BY
    m.machine_model;






